server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name findmylook.cs.colman.ac.il _;

    # Frontend
    location / {
        proxy_pass http://localhost:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Backend API
    location /api/ {
        client_max_body_size 20m;
        proxy_pass http://localhost:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ML Service
    location /ml/ {
        proxy_pass http://localhost:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    # Webhook
    location /webhook/ {
        proxy_pass http://localhost:9000/hooks/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
	proxy_set_header X-Hub-Signature $http_x_hub_signature;
	proxy_set_header X-Hub-Signature-256 $http_x_hub_signature_256;
    }

}
